script: add error check for robustness
Signed-off-by: Hiroshi Miura <miurahr@linux.com>

diff --git a/bin/tileman-load b/bin/tileman-load
--- a/bin/tileman-load
+++ b/bin/tileman-load
@@ -11,6 +11,7 @@
 # ----------------------------
 # ChnageLog
 #
+# 2013-10-21 add error check for robustness
 # 2013-07-02 change command name to tileman-load
 # ----------------------------
 #
@@ -44,14 +45,26 @@ fi
 
 if [ "$ORIGIN" = "planet" ]; then
   wget http://planet.openstreetmap.org/redaction-period/minute-replicate/state.txt
-  cp state.txt $WORKDIR_OSM/
-  wget http://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
-  /usr/bin/osm2pgsql $OPTIONS planet-latest.osm.pbf
+  if [ $? = 0 ]; then
+    cp state.txt $WORKDIR_OSM/
+    wget http://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
+    if [ $? = 0 ]; then
+      /usr/bin/osm2pgsql $OPTIONS planet-latest.osm.pbf
+    fi
+  fi
 elif [ "$ORIGIN" = "geofabrik" ]; then
   wget http://download.geofabrik.de/$REGION/$COUNTRY-updates/state.txt
-  cp state.txt $WORKDIR_OSM/
-  wget http://download.geofabrik.de/$REGION/$COUNTRY-latest.osm.pbf
-  /usr/bin/osm2pgsql $OPTIONS $COUNTRY-latest.osm.pbf
+  if [ $? = 0 ]; then
+    cp state.txt $WORKDIR_OSM/
+    wget http://download.geofabrik.de/$REGION/$COUNTRY-latest.osm.pbf
+    if [ $? = 0 ]; then
+      /usr/bin/osm2pgsql $OPTIONS $COUNTRY-latest.osm.pbf
+    else
+      echo "download error occured:" $ORIGIN
+    fi
+  else
+    echo "download error occured:" $ORIGIN
+  fi
 else
   echo Unknown origin $ORIGIN
 fi
diff --git a/bin/tileman-update b/bin/tileman-update
--- a/bin/tileman-update
+++ b/bin/tileman-update
@@ -114,12 +114,24 @@ shift $((OPTIND - 1))
 check_exec
 if [ "${TILE_UPDATE_FLAG}" = "yes" ]; then
   $OSMOSIS_BIN $OSMOSIS_OPT $OSC_PIPE
-  $OSM2PGSQL_BIN $OSM2PGSQL_OPT -o $EXPIRE_FILE $OSC_PIPE 
-  cat $EXPIRE_FILE | tileman-expconv $MAPNAME $MAXZOOM | $TIREX_BATCH_BIN -f $FILTER -p 10 &
-  cat $EXPIRE_FILE | tileman-expconv $MAPNAME $EXPIRE_ZOOM $MINZOOM | $TIREX_BATCH_BIN -f $FILTER -p 15 &
+  if [ $? = 0 ]; then
+    $OSM2PGSQL_BIN $OSM2PGSQL_OPT -o $EXPIRE_FILE $OSC_PIPE 
+    if [ $? = 0 ]; then
+      cat $EXPIRE_FILE | tileman-expconv $MAPNAME $MAXZOOM | $TIREX_BATCH_BIN -f $FILTER -p 10 &
+      cat $EXPIRE_FILE | tileman-expconv $MAPNAME $EXPIRE_ZOOM $MINZOOM | $TIREX_BATCH_BIN -f $FILTER -p 15 &
+    else
+      echo "error occured when " $OSM2PGSQL $OSM2PGSQL_OPT
+    fi
+  else
+    echo "error occured when " $OSMOSIS_BIN $OSMOSIS_OPT
+  fi
 else
   $OSMOSIS_BIN $OSMOSIS_OPT $OSC_PIPE
-  $OSM2PGSQL_BIN $OSM2PGSQL_OPT -o $EXPIRE_FILE $OSC_PIPE
+  if [ $? = 0 ]; then
+    $OSM2PGSQL_BIN $OSM2PGSQL_OPT -o $EXPIRE_FILE $OSC_PIPE
+  else
+    echo "error occured when " $OSMOSIS_BIN $OSMOSIS_OPT
+  fi
 fi
 rm -f $OSC_PIPE
 rm -f $EXPIRE_FILE
